### ISSUE TITLE
Computation failed in `stat_quiver()`: argument is of length zero 

### ISSUE THREAD

**Issue by mps9506** [mitchelloharawild/ggquiver#8]
Hi!
Thanks for this great package. `geom_quiver()` is returning the following warning (with no output) when I try to reproduce the examples in the package: 
```{r}
Warning message:
Computation failed in `stat_quiver()`:
argument is of length zero 
```

I noticed the pkgdown documentation is showing the same error.

Reprex:

```
library(ggplot2)
library(ggquiver)
library(dplyr)

expand.grid(x=seq(0,pi,pi/12), y=seq(0,pi,pi/12)) %>%
  ggplot(aes(x=x,y=y,u=cos(x),v=sin(y))) +
  geom_quiver()
```

Thanks!

**Comment by mitchelloharawild** [comment]
Fixed, thanks!

**Comment by mitchelloharawild** [comment]
A patch release has been submitted to CRAN.
