### ISSUE TITLE
geom_quiver does not work together with geom_sf 

### ISSUE THREAD

**Issue by RS-eco** [mitchelloharawild/ggquiver#9]
I want to create a plot with geom_quiver() and underlie a map. This works in the given example, when using borders():

```{r}
# Removing automatic scaling
ggplot(seals, aes(x=long, y=lat, u=delta_long, v=delta_lat)) +
  geom_quiver(vecsize=NULL) +
  borders("state")
```

but, I want to plot something similar using geom_sf() instead:

``` r
library(maps); library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
states <- sf::st_as_sf(map('usa', plot = FALSE, fill = TRUE))
ggplot() + geom_quiver(data=seals, aes(x=long, y=lat, u=delta_long, v=delta_lat), vecsize=NULL) + 
  geom_sf(data = states)
#> Error: $ operator is invalid for atomic vectors
```
Unfortunately, this throws up an error: **$ operator is invalid for atomic vectors**

**Comment by mitchelloharawild** [comment]
Thanks for the bug report, this is related to how the package handles coordinate systems.

**Comment by mitchelloharawild** [comment]
Fixed, thanks. I'll prepare a CRAN patch release shortly.

**Comment by mitchelloharawild** [comment]
On CRAN now as v0.3.2 (https://github.com/mitchelloharawild/ggquiver/releases/tag/v0.3.2)
